title: ifrance développements web
description: >-
  Vos plateformes, web apps et chat bots développés rapidement avec des outils
  modernes.
github_repo: jekyll
github_username: jekyll
social_link: twitter
social_username: jekyllrb
theme_color: black
remote_theme: broccolini/swiss
collections:
  - home
