title: Swiss Jekyll Theme
description: A bold typographic theme inspired by Swiss design.
github_repo: jekyll
github_username: jekyll
social_link: twitter
social_username: jekyllrb
theme_color: white
remote_theme: broccolini/swiss
